# Generated by Django 5.0 on 2024-03-28 11:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1924, 4, 22)), django.core.validators.MinValueValidator(datetime.date(2024, 3, 28))]),
        ),
    ]
