# Generated by Django 5.0 on 2024-04-20 10:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1924, 5, 15)), django.core.validators.MaxValueValidator(datetime.date(2024, 4, 20))]),
        ),
    ]
