# Generated by Django 5.0 on 2024-04-01 09:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+71234567890'. ", regex='\\+7\\d{10}')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1924, 4, 26)), django.core.validators.MaxValueValidator(datetime.date(2024, 4, 1))]),
        ),
    ]
