# Generated by Django 5.0 on 2024-04-08 11:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1924, 5, 3)), django.core.validators.MaxValueValidator(datetime.date(2024, 4, 8))]),
        ),
    ]
